version: 2.1

jobs:
  check_bootstrap:
    docker:
      - image: tuplestream/shellcheck:latest
    steps:
      - checkout
      - run: shellcheck ./bootstrap.bash
  build:
    docker:
      - image: tuplestream/golang:latest
    steps:
      - checkout
      - run: ./build.bash
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - checkout
      - run: bump
  release_build:
    docker:
      - image: tuplestream/golang:latest
    steps:
      - checkout
      - run:
          name: release build and push
          command: |
            git pull --no-edit origin master
            ./build.bash -release
      - persist_to_workspace:
          root: .
          paths:
            - bin/*
  github_release:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - checkout
      - run: git pull --no-edit origin master
      - attach_workspace:
          at: .
      - run: hub release create -a bin/tuplectl-linux-amd64 -a bin/tuplectl-darwin-amd64 -m $(cat VERSION) "v$(cat VERSION)"
  publish_bootstrap:
    docker:
      - image: tuplestream/aws-cli:latest
    steps:
      - checkout
      - run: aws s3 cp bootstrap.bash $S3_TARGET/bootstrap --acl public-read --content-type 'text/x-shellscript'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - check_bootstrap
      - bump_version:
          requires:
            - build
            - check_bootstrap
          filters:
            branches:
              only: master
      - release_build:
          requires:
            - bump_version
      - github_release:
          requires:
            - release_build
      - publish_bootstrap:
          requires:
            - release_build
