version: 2.1

jobs:
  build:
    docker:
      - image: tuplestream/golang:latest
    steps:
      - checkout
      - run: ./build.bash
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - checkout
      - run: bump
  release_build:
    docker:
      - image: tuplestream/golang:latest
    steps:
      - checkout
      - run:
          name: release build and push
          command: |
            git pull --no-edit origin master
            ./build.bash -release
      - persist_to_workspace:
          root: .
          paths:
            - bin/*
  github_release:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: hub release create -a bin/tuplectl-linux-amd64 -a bin/tuplectl-darwin-amd64 -m $(cat VERSION) "v$(cat VERSION)"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - bump_version:
          requires:
            - build
      - release_build:
          requires:
            - bump_version
      - github_release:
          requires:
            - release_build
