version: 2.1

jobs:
  check_bootstrap:
    docker:
      - image: tuplestream/shellcheck:latest
    steps:
      - checkout
      - run: shellcheck ./bootstrap.bash
  build:
    docker:
      - image: tuplestream/golang:latest
    steps:
      - checkout
      - run:
          name: run dev build
          command: |
            ./build.bash
            ./build.bash -release
      - persist_to_workspace:
          root: .
          paths:
            - bin/*
  lint_dockerfile:
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run: hadolint Dockerfile
  test_docker_build:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: attempt to build docker image
          command: |
            docker build . -t testimage
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - checkout
      - run: bump
  release_build:
    docker:
      - image: tuplestream/golang:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: release build and push
          command: |
            git pull --no-edit origin master
            ./build.bash -release
      - persist_to_workspace:
          root: .
          paths:
            - bin/*
  github_release:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - checkout
      - run: git pull --no-edit origin master
      - attach_workspace:
          at: .
      - run: hub release create -a bin/tuplectl-linux-amd64 -a bin/tuplectl-darwin-amd64 -m $(cat VERSION) "v$(cat VERSION)"
  docker_release:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - run: git pull --no-edit origin master
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: build and publish docker image
          command: |
            BUILDNAME="tuplectl"
            IMAGENAME="tuplestream/$BUILDNAME:$(cat VERSION)"
            IMAGE_LATEST="tuplestream/$BUILDNAME:latest"

            docker build . -t $IMAGENAME

            echo $DKPW | docker login --username $DOCKER_USER --password-stdin
            docker push $IMAGENAME
            docker tag $IMAGENAME $IMAGE_LATEST
            docker push $IMAGE_LATEST
  publish_bootstrap:
    docker:
      - image: tuplestream/aws-cli:latest
    steps:
      - checkout
      - run: aws s3 cp bootstrap.bash $S3_TARGET/bootstrap --acl public-read --content-type 'text/x-shellscript'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - check_bootstrap
      - lint_dockerfile
      - test_docker_build:
          requires:
            - lint_dockerfile
            - build
      - bump_version:
          requires:
            - check_bootstrap
            - test_docker_build
          filters:
            branches:
              only: master
      - release_build:
          requires:
            - bump_version
      - github_release:
          requires:
            - release_build
      - docker_release:
          requires:
            - release_build
      - publish_bootstrap:
          requires:
            - release_build
