version: 2.1

jobs:
  build:
    docker:
      - image: tuplestream/golang:latest
    steps:
      - checkout
      - run: ./build.bash
      - persist_to_workspace:
          root: .
          paths:
            - tuplectl
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - checkout
      - attach_workspace:
          at: tuplectl
      - run:
          name: bump version and perform release
          command: |
            bump

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - bump_version:
          requires:
            - build
