version: 2.1

jobs:
  build:
    docker:
      - image: tuplestream/golang:latest
    steps:
      - checkout
      - run: ./build.bash
      - persist_to_workspace:
          root: .
          paths:
            - tuplectl
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:24:38:64:d4:33:46:8c:fa:0a:30:e0:6e:4c:ef:8d"
      - checkout
      - run:
          name: run bumpversion and push
          command: bump

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - bump_version:
          requires:
            - build

